// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCcAD3gE2nvRV0FdhoOjl0yd6dGG-uLA',
    appId: '1:435301264595:web:e6abc2014cb8e8d097b826',
    messagingSenderId: '435301264595',
    projectId: 'artfolio-e9d2a',
    authDomain: 'artfolio-e9d2a.firebaseapp.com',
    storageBucket: 'artfolio-e9d2a.appspot.com',
    measurementId: 'G-334TFXF84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYPI5QXGGoy00AEIaKCQOYECkDAm0kH3c',
    appId: '1:435301264595:android:b655c2817fd20fe097b826',
    messagingSenderId: '435301264595',
    projectId: 'artfolio-e9d2a',
    storageBucket: 'artfolio-e9d2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsuoWFtYe5RmWgHcYCh34tFHK2e4axV0',
    appId: '1:435301264595:ios:2f5d28b0750c5ddb97b826',
    messagingSenderId: '435301264595',
    projectId: 'artfolio-e9d2a',
    storageBucket: 'artfolio-e9d2a.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdsuoWFtYe5RmWgHcYCh34tFHK2e4axV0',
    appId: '1:435301264595:ios:2f5d28b0750c5ddb97b826',
    messagingSenderId: '435301264595',
    projectId: 'artfolio-e9d2a',
    storageBucket: 'artfolio-e9d2a.appspot.com',
    iosBundleId: 'com.example.artfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCcAD3gE2nvRV0FdhoOjl0yd6dGG-uLA',
    appId: '1:435301264595:web:7c32c483857e293597b826',
    messagingSenderId: '435301264595',
    projectId: 'artfolio-e9d2a',
    authDomain: 'artfolio-e9d2a.firebaseapp.com',
    storageBucket: 'artfolio-e9d2a.appspot.com',
    measurementId: 'G-DTNVTK5C6J',
  );

}